# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [bfly]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: prod
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: oss-cn-hongkong.aliyuncs.com
          access-key-id: ${{ secrets.ALIYUN_OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_OSS_ACCESS_KEY_SECRET }}

      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.9.1
          run_install: true

      - name: build
        run: pnpm run build

      - run: ls && ossutil cp -rf dist oss://starcoin-mobius/

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
